void createControls() {
  cp5.addKnob("BPM")
   .setRange(20,360)
   .setValue(beats_per_minute)
   .setPosition(50,70)
   .setRadius(50)
   .setDragDirection(Knob.VERTICAL)
   ;
               
  cp5.addSlider("next_repeat_max")
     .setLabel("repeat")
     .setPosition(50,260)
     .setWidth(400)
     .setRange(1, 10)
     .setValue(repeat_max)
     .setNumberOfTickMarks(10)
     .setSliderMode(Slider.FLEXIBLE)
     ;
     
  // instrument 1
  cp5.addTextlabel("inst0_label")
     .setText("instrument 1")
     .setPosition(40,300)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst0")
     .setLabel("")
     .setPosition(110,300)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[0][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst0_vol")
     .setLabel("vol")
     .setPosition(400,300)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[0][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst0_den")
     .setLabel("den")
     .setPosition(520,300)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[0][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst0_sub")
     .setLabel("sub")
     .setPosition(640,300)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[0][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
     
  // instrument 2
  cp5.addTextlabel("inst1_label")
     .setText("instrument 2")
     .setPosition(40,330)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst1")
     .setLabel("")
     .setPosition(110,330)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[1][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst1_vol")
     .setLabel("vol")
     .setPosition(400,330)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[1][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst1_den")
     .setLabel("den")
     .setPosition(520,330)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[1][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst1_sub")
     .setLabel("sub")
     .setPosition(640,330)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[1][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ;   
     
  // instrument 3
  cp5.addTextlabel("inst2_label")
     .setText("instrument 3")
     .setPosition(40,360)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst2")
     .setLabel("")
     .setPosition(110,360)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[2][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst2_vol")
     .setLabel("vol")
     .setPosition(400,360)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[2][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst2_den")
     .setLabel("den")
     .setPosition(520,360)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[2][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst2_sub")
     .setLabel("sub")
     .setPosition(640,360)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[2][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ;   
     
   // instrument 4
  cp5.addTextlabel("inst3_label")
     .setText("instrument 4")
     .setPosition(40,390)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst3")
     .setLabel("")
     .setPosition(110,390)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[3][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst3_vol")
     .setLabel("vol")
     .setPosition(400,390)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[3][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst3_den")
     .setLabel("den")
     .setPosition(520,390)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[3][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst3_sub")
     .setLabel("sub")
     .setPosition(640,390)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[3][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ;  
  // instrument 5
  cp5.addTextlabel("inst4_label")
     .setText("instrument 5")
     .setPosition(40,420)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst4")
     .setLabel("")
     .setPosition(110,420)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[4][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst4_vol")
     .setLabel("vol")
     .setPosition(400,420)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[4][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst4_den")
     .setLabel("den")
     .setPosition(520,420)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[4][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst4_sub")
     .setLabel("sub")
     .setPosition(640,420)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[4][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ;   
  // instrument 6
  cp5.addTextlabel("inst5_label")
     .setText("instrument 6")
     .setPosition(40,450)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst5")
     .setLabel("")
     .setPosition(110,450)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[5][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst5_vol")
     .setLabel("vol")
     .setPosition(400,450)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[5][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst5_den")
     .setLabel("den")
     .setPosition(520,450)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[5][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst5_sub")
     .setLabel("sub")
     .setPosition(640,450)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[5][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ;  
     
     // instrument 7
  cp5.addTextlabel("inst6_label")
     .setText("instrument 7")
     .setPosition(40,480)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst6")
     .setLabel("")
     .setPosition(110,480)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[6][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst6_vol")
     .setLabel("vol")
     .setPosition(400,480)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[6][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst6_den")
     .setLabel("den")
     .setPosition(520,480)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[6][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst6_sub")
     .setLabel("sub")
     .setPosition(640,480)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[6][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
     
  // instrument 8
  cp5.addTextlabel("inst7_label")
     .setText("instrument 8")
     .setPosition(40,510)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst7")
     .setLabel("")
     .setPosition(110,510)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[7][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst7_vol")
     .setLabel("vol")
     .setPosition(400,510)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[7][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst7_den")
     .setLabel("den")
     .setPosition(520,510)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[7][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst7_sub")
     .setLabel("sub")
     .setPosition(640,510)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[7][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
     
  // instrument 9
  cp5.addTextlabel("inst8_label")
     .setText("instrument 9")
     .setPosition(40,540)
     .setColorValue(0xffffffff)
     ;
  cp5.addSlider("inst8")
     .setLabel("")
     .setPosition(110,540)
     .setWidth(80)
     .setRange(35, 81)
     .setValue(instruments[8][0])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst8_vol")
     .setLabel("vol")
     .setPosition(400,540)
     .setWidth(80)
     .setRange(0, 127)
     .setValue(instruments[8][4])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ;
  cp5.addSlider("inst8_den")
     .setLabel("den")
     .setPosition(520,540)
     .setWidth(80)
     .setRange(0, 100)
     .setValue(instruments[8][1])
     .setDecimalPrecision(1)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
   cp5.addSlider("inst8_sub")
     .setLabel("sub")
     .setPosition(640,540)
     .setWidth(200)
     .setRange(2, 32)
     .setValue(instruments[8][2])
     .setDecimalPrecision(1)
     .setNumberOfTickMarks(16)
     .setSliderMode(Slider.FLEXIBLE)
     ; 
}

void BPM(int theValue) {
  next_beats_per_minute = theValue;
}

void repeat(int val) {
  next_repeat_max = val;
}